import React, { useCallback, useState } from 'react';
import { PageShell } from '../components/layout';
import CustomDropdown from '../components/CustomDropdown';
import { CURRENCY_SYMBOLS } from '../constants';

const Settings = ({
  shellProps,
  currencyCode,
  setCurrencyCode,
  theme,
  toggleTheme,
  setView,
  session,
  handleLogout,
  transactions = [],
  accounts = [],
  categories = [],
  budgets = [],
  accountBalances = {},
  budgetProgress = [],
  currencySymbol = '$',
}) => {
  const [exportMonth, setExportMonth] = useState(() => new Date().toISOString().slice(0, 7));

  const generateMonthReport = useCallback(() => {
    const fmt = n => parseFloat(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    const [year, month] = exportMonth.split('-');
    const monthLabel = new Date(+year, +month - 1, 1).toLocaleDateString(undefined, { month: 'long', year: 'numeric' });

    const monthTx = transactions.filter(t => t.transaction_date?.startsWith(exportMonth));
    const regularTx = monthTx.filter(t => !t.transfer_id);
    const transferTx = monthTx.filter(t => t.transfer_id);

    // Category income
    const catIncome = {};
    regularTx.filter(t => t.type === 'income').forEach(t => {
      const k = t.categories?.name || 'Uncategorised';
      catIncome[k] = (catIncome[k] || 0) + parseFloat(t.amount);
    });
    const totalIncome = Object.values(catIncome).reduce((s, v) => s + v, 0);

    // Category spending
    const catSpend = {};
    regularTx.filter(t => t.type === 'expense').forEach(t => {
      const k = t.categories?.name || 'Uncategorised';
      catSpend[k] = (catSpend[k] || 0) + parseFloat(t.amount);
    });
    const totalExpense = Object.values(catSpend).reduce((s, v) => s + v, 0);

    let md = `# MOMA Monthly Report — ${monthLabel}\n`;
    md += `**Currency:** ${currencyCode} | **Generated:** ${new Date().toISOString().split('T')[0]}\n\n---\n\n`;

    md += `## Summary\n`;
    md += `- **Total Income:** ${currencySymbol}${fmt(totalIncome)}\n`;
    md += `- **Total Spending:** ${currencySymbol}${fmt(totalExpense)}\n`;
    md += `- **Net:** ${currencySymbol}${fmt(totalIncome - totalExpense)}\n\n`;

    md += `## Income by Category\n`;
    if (Object.keys(catIncome).length === 0) {
      md += `No income this month.\n`;
    } else {
      Object.entries(catIncome).sort((a, b) => b[1] - a[1]).forEach(([name, amt]) => {
        const pct = totalIncome > 0 ? ((amt / totalIncome) * 100).toFixed(1) : '0.0';
        md += `- **${name}:** ${currencySymbol}${fmt(amt)} (${pct}%)\n`;
      });
    }

    md += `\n## Spending by Category\n`;
    if (Object.keys(catSpend).length === 0) {
      md += `No expenses this month.\n`;
    } else {
      Object.entries(catSpend).sort((a, b) => b[1] - a[1]).forEach(([name, amt], i) => {
        const pct = totalExpense > 0 ? ((amt / totalExpense) * 100).toFixed(1) : '0.0';
        const budget = budgetProgress.find(b => categories.find(c => c.id === b.category_id)?.name === name);
        const budgetNote = budget ? ` | budget ${currencySymbol}${fmt(budget.limit_amount)} — ${budget.status === 'over' ? 'OVER' : 'ok'}` : '';
        md += `${i + 1}. **${name}:** ${currencySymbol}${fmt(amt)} (${pct}%)${budgetNote}\n`;
      });
    }

    md += `\n## All Transactions\n`;
    md += `| Date | Description | Category | Account | Amount | Type |\n`;
    md += `|------|-------------|----------|---------|--------|------|\n`;
    [...regularTx].sort((a, b) => (b.transaction_date || '').localeCompare(a.transaction_date || '')).forEach(t => {
      const desc = t.parties?.name || t.note || '-';
      const cat = t.categories?.name || '-';
      const acct = accounts.find(a => a.id === t.account_id)?.name || '-';
      const sign = t.type === 'income' ? '+' : '-';
      md += `| ${t.transaction_date} | ${desc} | ${cat} | ${acct} | ${sign}${currencySymbol}${fmt(t.amount)} | ${t.type} |\n`;
    });

    if (transferTx.length > 0) {
      const seenIds = new Set();
      md += `\n## Transfers\n`;
      md += `| Date | Note | From | To | Amount |\n`;
      md += `|------|------|------|----|--------|\n`;
      transferTx.forEach(t => {
        if (seenIds.has(t.transfer_id)) return;
        seenIds.add(t.transfer_id);
        const expLeg = transferTx.find(x => x.transfer_id === t.transfer_id && x.type === 'expense');
        const incLeg = transferTx.find(x => x.transfer_id === t.transfer_id && x.type === 'income');
        const from = accounts.find(a => a.id === expLeg?.account_id)?.name || '-';
        const to = accounts.find(a => a.id === incLeg?.account_id)?.name || '-';
        md += `| ${t.transaction_date} | ${t.note || '-'} | ${from} | ${to} | ${currencySymbol}${fmt(t.amount)} |\n`;
      });
    }

    md += `\n---\n*Generated by MOMA. Paste into Claude or Gemini for AI-powered financial advice.*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `moma-${exportMonth}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [exportMonth, transactions, accounts, categories, budgets, budgetProgress, accountBalances, currencySymbol, currencyCode]);

  const generateAIReport = useCallback(() => {
    const today = new Date();
    const dateStr = today.toISOString().split('T')[0];
    const monthLabel = today.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
    const currentMonth = today.toISOString().slice(0, 7);
    const fmt = n => parseFloat(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

    const netWorth = Object.values(accountBalances).reduce((s, v) => s + v, 0);

    const currentMonthTx = transactions.filter(t => t.transaction_date?.startsWith(currentMonth) && !t.transfer_id);
    const currentIncome = currentMonthTx.filter(t => t.type === 'income').reduce((s, t) => s + parseFloat(t.amount), 0);
    const currentExpense = currentMonthTx.filter(t => t.type === 'expense').reduce((s, t) => s + parseFloat(t.amount), 0);

    const catSpend = {};
    currentMonthTx.filter(t => t.type === 'expense' && t.categories).forEach(t => { const k = t.categories.name; catSpend[k] = (catSpend[k] || 0) + parseFloat(t.amount); });
    const topCats = Object.entries(catSpend).sort((a, b) => b[1] - a[1]);

    const monthlyTotals = {};
    transactions.filter(t => !t.transfer_id).forEach(t => { const m = t.transaction_date?.slice(0, 7); if (!m) return; if (!monthlyTotals[m]) monthlyTotals[m] = { income: 0, expense: 0 }; if (t.type === 'income') monthlyTotals[m].income += parseFloat(t.amount); else monthlyTotals[m].expense += parseFloat(t.amount); });
    const last3Months = Object.entries(monthlyTotals).sort(([a], [b]) => b.localeCompare(a)).slice(0, 3);

    const recentTx = transactions.filter(t => !t.transfer_id).slice(0, 20);

    let md = `# MOMA Financial Context\n**Generated:** ${dateStr} | **Currency:** ${currencyCode}\n\n---\n\n`;
    md += `## Financial Snapshot\n- **Net Worth:** ${currencySymbol}${fmt(netWorth)}\n- **This Month (${monthLabel}):** Income ${currencySymbol}${fmt(currentIncome)} | Expenses ${currencySymbol}${fmt(currentExpense)}\n\n`;
    md += `## Account Balances\n${accounts.map(a => `- ${a.name}: ${currencySymbol}${fmt(accountBalances[a.id] || 0)}`).join('\n')}\n\n`;
    md += `## Spending by Category (${monthLabel})\n`;
    if (topCats.length === 0) { md += `No expense transactions this month.\n`; }
    else { topCats.forEach(([name, amt], i) => { const b = budgetProgress.find(b => categories.find(c => c.id === b.category_id)?.name === name); const budgetNote = b ? ` (budget: ${currencySymbol}${fmt(b.limit_amount)} — ${b.status === 'over' ? 'OVER BUDGET' : 'ok'})` : ''; md += `${i + 1}. ${name}: ${currencySymbol}${fmt(amt)}${budgetNote}\n`; }); }
    md += `\n## Budget Status\n`;
    if (budgetProgress.length === 0) { md += `No budgets configured.\n`; }
    else { budgetProgress.forEach(b => { const cat = categories.find(c => c.id === b.category_id); md += `- ${cat?.name || 'Global'}: ${currencySymbol}${fmt(b.spent)} / ${currencySymbol}${fmt(b.limit_amount)} ${b.status === 'over' ? '[OVER]' : '[ok]'}\n`; }); }
    md += `\n## Monthly Trends (Last 3 Months)\n`;
    last3Months.forEach(([month, t]) => { md += `- ${month}: Income ${currencySymbol}${fmt(t.income)} | Expenses ${currencySymbol}${fmt(t.expense)} | Net ${currencySymbol}${fmt(t.income - t.expense)}\n`; });
    md += `\n## Recent Transactions (Last 20)\n| Date | Description | Category | Amount | Type |\n|------|-------------|----------|--------|------|\n`;
    recentTx.forEach(t => { const desc = t.parties?.name || t.note || '-'; const cat = t.categories?.name || '-'; const sign = t.type === 'income' ? '+' : '-'; md += `| ${t.transaction_date} | ${desc} | ${cat} | ${sign}${currencySymbol}${fmt(t.amount)} | ${t.type} |\n`; });
    md += `\n---\n*Paste this report into Claude or Gemini for AI-powered financial advice.*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `moma-context-${dateStr}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [transactions, accounts, categories, budgets, accountBalances, budgetProgress, currencySymbol, currencyCode]);
  const currencyOptions = Object.entries(CURRENCY_SYMBOLS).map(([code, sym]) => ({ 
    value: code, 
    label: code + ' (' + sym + ')',
    icon: 'payments'
  }));

  return (
    <PageShell {...shellProps}>
      <div className="page-inner max-w-2xl mx-auto space-y-12 pb-32 pt-4 md:pt-0 px-6">
        <div className="flex justify-between items-center px-4">
          <h2 className="font-headline text-4xl font-black tracking-tight text-on-surface uppercase">Vault Core</h2>
        </div>

        <div className="space-y-12">
          {/* Preferences Section */}
          <section className="space-y-6">
            <p className="text-[10px] font-black tracking-[0.4em] text-on-surface-variant uppercase px-4 opacity-60">System Config</p>
            <div className="bg-surface-low rounded-[2.5rem] border border-outline-variant/10 overflow-hidden divide-y divide-outline-variant/5 shadow-2xl">
              <div className="p-8 flex flex-col sm:flex-row sm:items-center justify-between gap-6 hover:bg-on-surface/[0.02] transition-colors group">
                <div className="flex items-center gap-5">
                  <div className="w-12 h-12 rounded-2xl bg-on-surface/[0.03] flex items-center justify-center text-on-surface-variant group-hover:text-primary transition-colors">
                    <span className="material-symbols-outlined text-[22px]">currency_exchange</span>
                  </div>
                  <div>
                    <p className="text-sm font-bold text-on-surface">Base Currency</p>
                    <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mt-1 opacity-60">Primary display unit</p>
                  </div>
                </div>
                <div className="w-full sm:w-56">
                  <CustomDropdown options={currencyOptions} value={currencyCode} onChange={setCurrencyCode} showSearch={true} />
                </div>
              </div>
            </div>
          </section>

          {/* Management Section */}
          <section className="space-y-6">
            <p className="text-[10px] font-black tracking-[0.4em] text-on-surface-variant uppercase px-4 opacity-60">Hierarchy Engine</p>
            <div className="bg-surface-low rounded-[2.5rem] border border-outline-variant/10 overflow-hidden divide-y divide-outline-variant/5 shadow-2xl">
              {[
                { key: 'account_management', label: 'Vault Entities', icon: 'account_balance', desc: 'Accounts, banks, and assets' },
                { key: 'category_management', label: 'Taxonomy', icon: 'category', desc: 'Transaction classifications' },
                { key: 'party_management', label: 'Nodes', icon: 'storefront', desc: 'Frequent payees and sources' },
                { key: 'tag_management', label: 'Metadata', icon: 'label', desc: 'Granular analytical labels' }
              ].map(item => (
                <button 
                  key={item.key}
                  className="w-full p-8 flex items-center justify-between group hover:bg-on-surface/[0.02] transition-all text-left"
                  onClick={() => setView(item.key)}
                >
                  <div className="flex items-center gap-5">
                    <div className="w-12 h-12 rounded-2xl bg-on-surface/[0.03] flex items-center justify-center text-on-surface-variant group-hover:text-primary transition-colors border border-outline-variant/5">
                      <span className="material-symbols-outlined text-[22px]">{item.icon}</span>
                    </div>
                    <div>
                      <p className="text-sm font-bold text-on-surface group-hover:text-primary transition-colors">{item.label}</p>
                      <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mt-1 opacity-60">{item.desc}</p>
                    </div>
                  </div>
                  <span className="material-symbols-outlined text-on-surface-variant group-hover:text-primary transition-all group-hover:translate-x-1 opacity-40">chevron_right</span>
                </button>
              ))}
            </div>
          </section>

          {/* AI Integration Section */}
          <section className="space-y-6">
            <p className="text-[10px] font-black tracking-[0.4em] text-on-surface-variant uppercase px-4 opacity-60">Intelligence</p>
            <div className="bg-surface-low rounded-[2.5rem] border border-outline-variant/10 overflow-hidden shadow-2xl divide-y divide-outline-variant/5">
              {/* Monthly report with month picker */}
              <div className="p-8 flex flex-col sm:flex-row sm:items-center justify-between gap-6 group hover:bg-on-surface/[0.02] transition-all">
                <div className="flex items-center gap-5">
                  <div className="w-12 h-12 rounded-2xl bg-on-surface/[0.03] flex items-center justify-center text-on-surface-variant border border-outline-variant/5 shrink-0">
                    <span className="material-symbols-outlined text-[22px]">calendar_month</span>
                  </div>
                  <div>
                    <p className="text-sm font-bold text-on-surface">Monthly Report</p>
                    <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mt-1 opacity-60">Category breakdown + all transactions</p>
                  </div>
                </div>
                <div className="flex items-center gap-3 shrink-0">
                  <input
                    type="month"
                    value={exportMonth}
                    onChange={e => setExportMonth(e.target.value)}
                    className="bg-surface-lowest border border-outline-variant/20 rounded-2xl px-4 py-2.5 text-sm font-bold text-on-surface outline-none focus:ring-2 focus:ring-primary/10 transition-all"
                  />
                  <button
                    onClick={generateMonthReport}
                    className="w-10 h-10 rounded-2xl bg-on-surface text-surface flex items-center justify-center hover:brightness-110 active:scale-95 transition-all shadow-lg"
                    title="Download report"
                  >
                    <span className="material-symbols-outlined text-[18px]">download</span>
                  </button>
                </div>
              </div>
              {/* Full context snapshot */}
              <button
                className="w-full p-8 flex items-center justify-between group hover:bg-on-surface/[0.02] transition-all text-left"
                onClick={generateAIReport}
              >
                <div className="flex items-center gap-5">
                  <div className="w-12 h-12 rounded-2xl bg-on-surface/[0.03] flex items-center justify-center text-on-surface-variant group-hover:text-primary transition-colors border border-outline-variant/5">
                    <span className="material-symbols-outlined text-[22px]">model_training</span>
                  </div>
                  <div>
                    <p className="text-sm font-bold text-on-surface group-hover:text-primary transition-colors">Full Context Snapshot</p>
                    <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mt-1 opacity-60">Net worth, trends, recent 20 tx</p>
                  </div>
                </div>
                <span className="material-symbols-outlined text-on-surface-variant group-hover:text-primary transition-all opacity-40">download</span>
              </button>
            </div>
          </section>

          {/* User Section */}
          <section className="space-y-6">
            <p className="text-[10px] font-black tracking-[0.4em] text-on-surface-variant uppercase px-4 opacity-60">Access Control</p>
            <div className="bg-surface-low p-10 rounded-[2.5rem] border border-outline-variant/10 shadow-2xl space-y-10">
              <div className="flex items-center gap-6">
                <div className="w-16 h-16 rounded-3xl bg-on-surface text-surface flex items-center justify-center font-black text-2xl shadow-xl">
                  {session?.user?.email?.charAt(0).toUpperCase()}
                </div>
                <div>
                  <p className="text-lg font-black text-on-surface tracking-tight leading-none">{session?.user?.email}</p>
                  <p className="text-[10px] font-black text-accent uppercase tracking-[0.2em] mt-2">Vault Protocol Active</p>
                </div>
              </div>
              <button 
                className="w-full bg-on-surface/[0.03] text-on-surface hover:bg-error hover:text-on-primary py-5 rounded-2xl font-black text-[11px] uppercase tracking-[0.3em] flex items-center justify-center gap-4 border border-outline-variant/10 transition-all active:scale-[0.98] group"
                onClick={handleLogout}
              >
                <span className="material-symbols-outlined text-[18px] group-hover:scale-110 transition-transform">power_settings_new</span>
                De-Authorize Vault
              </button>
            </div>
          </section>
        </div>
      </div>
    </PageShell>
  );
};

export default Settings;
